# This is a workflow to automate testing using a docker image of juice-shop and locally installed htcap
name: run_htcap_juiceshop
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      #- name: Setup dependencies
      #  run: |
      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - run: |
          echo "Start sleep 10s"
          sleep 10
      - name: Run htcap
        run: |
          cd ./run_scripts/htcap/juiceshop          
          python 2_htcap.py
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: htcap_report
          path: ./reports/htcap_juiceshop_report.html