# This is a workflow to automate testing using a docker image of juice-shop and locally installed htcap
name: run_htcap_juiceshop
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      #- name: Setup dependencies
      #  run: |
      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - run: |
          cd ./htcap
          docker build -t htcap --build-arg HTCAP_VERSION=master .
          mkdir -p htcap-out && docker run -v "$(pwd)/htcap-out/":/out/ --rm --name htcap htcap
          docker exec -it htcap bash
          cd ../run_scripts/htcap/juiceshop          
          python 2_htcap.py
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: htcap_report
          path: ./reports/htcap_juiceshop_report.html