# This is a workflow to automate testing using a docker image of juice-shop and locally installed ZAP
name: ZAP_test
on:
  # Run manually
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - name: Run htcap
        run: |
          cd /home/bart/fuzzingNode.jsApplications/run_scripts/htcap
          python 2_htcap.py
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: ZAP_report
          path: ./reports/htcap_juiceshop_report.html