# This is a workflow to automate testing using a docker image of juice-shop and locally installed ZAP
name: run_htcap_juiceshop
on:
  # Run manually
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      #- name: Setup dependencies
      #  run: |
      #    sudo apt-get update
      #    curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -
      #    sudo apt-get install -y nodejs
      #    sudo apt-get install -y build-essential
      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - run: |
          echo "Start sleep 10s"
          sleep 10
          echo "Finished sleep"
      - name: Run htcap
        run: |
          # cd ./run_scripts/htcap/juiceshop          
          # python 2_htcap.py
          cd ./htcap          
          ./htcap.py crawl -w -t 20 -x http://localhost:3000/redirect. http://localhost:3000 ../.github/home/htcap_juiceshop_report.db
        uses: actions/upload-artifact@v2
        with:
          name: htcap_db
          path: ./.github/home/htcap_juiceshop_report.db
      # - name: run scan here
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: htcap_report
          path: ./reports/htcap_juiceshop_report.html
