# This is a workflow to automate testing using mongo-express and ZAP
name: run_zap_mongoexpress
on:
  workflow_dispatch:
jobs:
  setup:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade zapcli
      - name: Setup environment variables
        run: |
          echo "ZAP_PATH=./ZAP_2.10.0/zap.sh" >> $GITHUB_ENV
          echo "ZAP_PORT=8080" >> $GITHUB_ENV
          echo "ZAP_URL=http://localhost" >> $GITHUB_ENV
      - name: Get Mongodb
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod          
      - name: Get Mongo-Express
        run: |
          sudo npm install -g mongo-express
      - name: Set custom config.js for express
        run: |
          sudo mv ./config.js /usr/local/lib/node_modules/mongo-express/
      - name: Install pymongo
        run: |
          pip install pymongo
      - name: Initialise mongodb "exampledb"
        run: |
          cd ./run_scripts/zap/mongo-express
          python 4_mongodb_init.py
  detach:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Start mongo-express
        run: |
          mongo-express -H localhost -P 27017
  launch:
    needs: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run ZAP
        run: ./ZAP_2.10.0/zap.sh -daemon -config api.disablekey=true -config ajaxSpider.maxDuration=180 > /dev/null &
      - name: Wait for ZAP to boot
        run: |
          echo "Sleeping..."
          sleep 20
      - name: Attack mongo
        run: |
          cd ./run_scripts/zap/mongo-express
          python 3_attack.py         
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: ZAP_report
          path: ./reports/zap_mongoexpress_report.html