# This is a workflow to automate testing using a docker image of juice-shop and locally installed ZAP
name: run_w3af_juiceshop
on:
  # Run manually
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python2.7-minimal
      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - name: Pull w3af from repo
        run: |
          git clone https://github.com/andresriancho/w3af.git
      - name: Run w3af
        run: |
          cd ./w3af/extras/docker/scripts
          sudo /usr/bin/python2.7 w3af_console_docker > /dev/null &
      - name: Wait for w3af to boot
        run: |
          echo "Start sleep 20s"
          sleep 20
          echo "Finished sleep"
      - name: Attack with w3af
        run: |
          cd ./run_scripts/w3af/juiceshop
          python w3af_attack.py