# This is a workflow to automate testing using a docker image of juice-shop and locally installed ZAP
name: run_w3af_juiceshop
on:
  # Run manually
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install python2.7-minimal
          sudo apt-get install w3af
      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - name: Wait for juiceshop to load
        run: |
          echo "Start sleep 20s"
          sleep 20
          echo "Finished sleep"
      - name: Attack juice-shop
      - name: Run w3af attack script
        run: w3af_console -s ./run_scripts/w3af/juiceshop/w3af_attack.w3af
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: w3af_report
          path: /usr/share/w3af/report.html