name: run_wapiti_juiceshop
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install wapiti
        run: |
          pip install wapiti3
      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - run: |
          echo "Start sleep 20s"
          sleep 20
          echo "Finished sleep"
      - name: Run wapiti
        run: |
          cd ./run_scripts/wapiti/juiceshop          
          python 2_wapiti.py
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: wapiti_juiceshop_report
          path: ./reports/wapiti/juiceshop/*
