# This is a workflow to automate testing using a docker image of nodegoat and wapiti
name: run_wapiti_juiceshop
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade zapcli
          # install mongo db
          wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
          sudo systemctl status mongod
      - name: Install wapiti
        run: |
          pip install wapiti3
      - name: Run NodeGoat
        run: |
          cd ./nodegoat/NodeGoat
          sudo systemctl start mongod
          npm run db:seed
          docker-compose build
          docker-compose up -d
      - run: |
          echo "Start sleep 10s"
          sleep 10
          echo "Finished sleep"
      - name: Run wapiti
        run: |
          cd ./run_scripts/wapiti/nodegoat         
          python 2_wapiti.py
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: wapiti_report
          path: ./reports/wapiti/wapiti_nodegoat_report.html
