# This is a workflow to automate testing using a docker image of juice-shop and locally installed ZAP
name: ZAP_test
on:
  # Run manually
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade zapcli
      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run -d -p 3000:3000 bkimminich/juice-shop
      - name: Run ZAP
        run: ./ZAP_2.10.0/zap.sh -daemon -config ajaxSpider.maxDuration=180 > /dev/null &
      - name: Wait for ZAP to boot
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'
      - name: Attack juice-shop
        run: |
          cd ./run_scripts/zap/juiceshop
          python 3_attack.py
      - name: Export artifact
        uses: actions/upload-artifact@v2
        with:
          name: ZAP_report
          path: ./reports/zap_juiceshop_report.html