# This is a basic workflow to help you get started with Actions

name: ZAP_test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      -name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade zapcli

      - name: Pull and run juice-shop
        run: |
          docker pull bkimminich/juice-shop
          docker run --rm -p 3000:3000 bkimminich/juice-shop
      
      -name: Run ZAP
        run: ./ZAP_2.10.0/zap.sh-daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=".*" -config api.addrs.addr.regex=true -ajaxSpider.maxDuration=180', shell=True > /dev/null &

      -name: Wait for ZAP to boot
        uses: jakejarvis/wait-action@master
        with:
          time: '20s'

      -name: Attack juice-shop
        run: |
          cd ./run_scripts/zap/juiceshop
          python 3_attack.py

